//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminID { get; set; }
        public int MunicipalityID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdateddAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string Password { get; set; }
    
        public virtual Municipality Municipality { get; set; }
    }
}
